import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const amountEntryStyles = StyleSheet.create({
  container: {
    width: '100%',
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 16,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textHeader,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textSupplementary,
    fontWeight: '500',
    textAlign: 'center',
  },
  primaryRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
  },
  primaryInput: {
    fontSize: 48,
    fontWeight: '700',
    color: colors.brandPink,
    textAlign: 'center',
    minWidth: 120,
    paddingVertical: 0,
  },
  primaryUnit: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.brandPink,
  },
  secondaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  secondaryText: {
    fontSize: 14,
    color: colors.textBody,
    fontWeight: '600',
  },
  secondaryUnit: {
    fontSize: 14,
    color: colors.brandPink,
    fontWeight: '700',
  },
  swapIcon: {
    fontSize: 14,
    color: colors.textSupplementary,
    fontWeight: '600',
  },
  rangeText: {
    fontSize: 12,
    color: colors.textSupplementary,
  },
  warningText: {
    fontSize: 12,
    color: colors.red,
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 'auto',
    paddingTop: 16,
  },
  backButton: {
    backgroundColor: colors.white,
    height: 52,
    paddingHorizontal: 30,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  backButtonText: {
    color: colors.brandPink,
    fontSize: 16,
    fontWeight: '700',
  },
  confirmButton: {
    backgroundColor: colors.brandPink,
    height: 52,
    paddingHorizontal: 30,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
});
