import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerContainer: {
    height: 280,
    position: 'relative',
  },
  headerImage: {
    width: '100%',
    height: '100%',
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  backButton: {
    position: 'absolute',
    top: 44,
    left: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.brandPink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backArrow: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '700',
    marginTop: -2,
  },
  headerContent: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    right: 20,
  },
  headerTitle: {
    color: colors.white,
    fontSize: 32,
    fontWeight: '700',
  },
  headerMeta: {
    color: colors.white,
    fontSize: 14,
    opacity: 0.85,
    marginTop: 4,
  },
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    gap: 12,
    paddingBottom: 40,
  },
  description: {
    fontSize: 14,
    color: colors.textBody,
    lineHeight: 22,
    marginBottom: 4,
  },
  missionCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  missionThumb: {
    width: 80,
    height: 45,
    borderRadius: 8,
  },
  missionRight: {
    flex: 1,
    gap: 2,
  },
  missionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textHeader,
  },
  missionMeta: {
    fontSize: 12,
    color: colors.textSupplementary,
  },
  checkCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.green,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkMark: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '700',
  },
  chipStart: {
    backgroundColor: colors.brandPink,
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 100,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  chipStartText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  chipEarned: {
    backgroundColor: colors.greenLight,
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 100,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  chipEarnedText: {
    color: colors.greenDark,
    fontSize: 11,
    fontWeight: '700',
  },
  rewardBanner: {
    backgroundColor: colors.greenLight,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  rewardText: {
    color: colors.greenDark,
    fontSize: 14,
    fontWeight: '700',
  },
  chipComingSoon: {
    backgroundColor: colors.divider,
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 100,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  chipComingSoonText: {
    color: colors.textSupplementary,
    fontSize: 11,
    fontWeight: '700',
  },
  tipButton: {
    backgroundColor: colors.brandPink,
    height: 52,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tipButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
});
