import { StyleSheet } from 'react-native';
import type { Palette } from './palettes';

export const createReceiveSheetStyles = (colors: Palette) =>
  StyleSheet.create({
    sheetBackground: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    handleIndicator: {
      backgroundColor: colors.divider,
      width: 40,
    },
    content: {
      flex: 1,
    },
    innerContent: {
      padding: 20,
      paddingBottom: 40,
      alignItems: 'center',
      gap: 12,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textHeader,
    },
    tabRow: {
      flexDirection: 'row',
      backgroundColor: colors.divider,
      borderRadius: 10,
      padding: 3,
    },
    tab: {
      paddingHorizontal: 24,
      paddingVertical: 8,
      borderRadius: 8,
    },
    tabActive: {
      backgroundColor: colors.surface,
    },
    tabText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSupplementary,
    },
    tabTextActive: {
      color: colors.brandPink,
    },
    amountSection: {
      alignItems: 'center',
      gap: 4,
    },
    amountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    amountInput: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      width: 100,
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
    },
    unitButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.divider,
    },
    unitButtonActive: {
      backgroundColor: colors.brandPink,
    },
    unitButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textSupplementary,
    },
    unitButtonTextActive: {
      color: colors.white,
    },
    convertedAmount: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '500',
      minHeight: 18,
    },
    qrContainer: {
      width: 220,
      height: 220,
      borderRadius: 24,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.background,
    },
    checkmark: {
      position: 'absolute',
      top: -20,
      right: -20,
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.green,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkmarkText: {
      color: colors.white,
      fontSize: 28,
      fontWeight: '700',
    },
    noInvoice: {
      color: colors.textSupplementary,
      fontSize: 14,
      textAlign: 'center',
      padding: 20,
    },
    qrLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    addressHighlight: {
      color: colors.green,
      fontWeight: '700',
    },
    invoiceText: {
      color: colors.textSupplementary,
      fontSize: 11,
      textAlign: 'center',
      paddingHorizontal: 20,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 10,
      alignSelf: 'stretch',
    },
    actionButton: {
      flex: 1,
      minWidth: 0,
      backgroundColor: colors.surface,
      height: 52,
      paddingHorizontal: 12,
      borderRadius: 12,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    actionButtonDisabled: {
      opacity: 0.4,
      elevation: 0,
      shadowOpacity: 0,
    },
    actionButtonPrimary: {
      backgroundColor: colors.brandPink,
    },
    actionButtonText: {
      color: colors.brandPink,
      fontSize: 15,
      fontWeight: '700',
    },
    actionButtonTextPrimary: {
      color: colors.white,
    },
    walletDropdownRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    walletDropdownWrapper: {
      position: 'relative',
      zIndex: 10,
    },
    walletDropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 8,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.divider,
    },
    walletDropdownText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    walletDropdownArrow: {
      fontSize: 10,
      color: colors.textSupplementary,
    },
    walletDropdownMenu: {
      position: 'absolute',
      top: '100%',
      left: 0,
      right: 0,
      marginTop: 4,
      backgroundColor: colors.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.divider,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      overflow: 'hidden',
      minWidth: 160,
    },
    walletDropdownItem: {
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    walletDropdownItemActive: {
      backgroundColor: colors.brandPink,
    },
    walletDropdownItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    walletDropdownItemTextActive: {
      color: colors.white,
    },
    walletLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSupplementary,
    },
    amountSummary: {
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
    },
    amountSummaryLine: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
    },
    amountSummaryValue: {
      fontSize: 44,
      fontWeight: '700',
      color: colors.brandPink,
      letterSpacing: 0.5,
      lineHeight: 44,
      includeFontPadding: false,
    },
    amountSummaryUnit: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.brandPink,
      marginTop: 6,
      letterSpacing: 1,
    },
    amountSummaryFiat: {
      fontSize: 14,
      color: colors.textSupplementary,
      fontWeight: '600',
    },
    enterAmountButton: {
      alignSelf: 'center',
      marginTop: 16,
      backgroundColor: colors.surface,
      paddingHorizontal: 24,
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    enterAmountText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textBody,
    },
    changeAmountButton: {
      marginTop: 8,
      backgroundColor: colors.surface,
      paddingHorizontal: 24,
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    changeAmountText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textBody,
    },
    // "Show my address" — lower-emphasis than Change amount, takes the
    // user back to the lud16 QR after an invoice has been generated.
    secondaryActionButton: {
      marginTop: 4,
      paddingVertical: 10,
      alignItems: 'center',
    },
    secondaryActionText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.brandPink,
    },
  });
