import { StyleSheet } from 'react-native';
import type { Palette } from './palettes';

export const createSendSheetStyles = (colors: Palette) =>
  StyleSheet.create({
    sheetBackground: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    handleIndicator: {
      backgroundColor: colors.divider,
      width: 40,
    },
    content: {
      flex: 1,
    },
    innerContent: {
      padding: 20,
      paddingBottom: 40,
      alignItems: 'center',
      gap: 14,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textHeader,
    },
    tabRow: {
      flexDirection: 'row',
      backgroundColor: colors.divider,
      borderRadius: 10,
      padding: 3,
    },
    tab: {
      paddingHorizontal: 24,
      paddingVertical: 8,
      borderRadius: 8,
    },
    tabActive: {
      backgroundColor: colors.surface,
    },
    tabText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSupplementary,
    },
    tabTextActive: {
      color: colors.brandPink,
    },
    cameraContainer: {
      width: 240,
      height: 240,
      borderRadius: 24,
      backgroundColor: colors.surface,
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.background,
    },
    camera: {
      width: '100%',
      height: '100%',
    },
    permissionContainer: {
      padding: 20,
      alignItems: 'center',
      gap: 12,
    },
    permissionText: {
      color: colors.textBody,
      fontSize: 14,
      textAlign: 'center',
    },
    permissionButton: {
      backgroundColor: colors.brandPink,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    permissionButtonText: {
      color: colors.white,
      fontWeight: '700',
    },
    pasteSection: {
      width: '100%',
      gap: 12,
    },
    pasteInput: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      fontSize: 14,
      color: colors.textBody,
      minHeight: 100,
      textAlignVertical: 'top',
    },
    pasteButtonRow: {
      flexDirection: 'row',
      gap: 10,
    },
    pasteButton: {
      flex: 1,
      backgroundColor: colors.divider,
      height: 44,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pasteButtonText: {
      color: colors.textBody,
      fontSize: 14,
      fontWeight: '600',
    },
    goButton: {
      backgroundColor: colors.brandPink,
      height: 44,
      paddingHorizontal: 24,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    goButtonDisabled: {
      opacity: 0.5,
    },
    goButtonText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
    },
    detailsCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      width: '100%',
      alignItems: 'center',
      gap: 12,
    },
    recipientPicture: {
      width: 48,
      height: 48,
      borderRadius: 24,
    },
    detailDescription: {
      fontSize: 14,
      color: colors.textBody,
      textAlign: 'center',
    },
    amountSection: {
      alignItems: 'center',
      gap: 4,
    },
    amountPickerRow: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: colors.brandPinkLight,
      borderWidth: 1,
      borderColor: colors.brandPink,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 180,
    },
    amountPickerValue: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.brandPink,
    },
    amountPickerFiat: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '600',
      marginTop: 2,
    },
    amountPickerPlaceholder: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.brandPink,
    },
    amountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    amountInput: {
      backgroundColor: colors.background,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      width: 100,
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
      color: colors.textBody,
    },
    unitButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.divider,
    },
    unitButtonActive: {
      backgroundColor: colors.brandPink,
    },
    unitButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textSupplementary,
    },
    unitButtonTextActive: {
      color: colors.white,
    },
    convertedAmount: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '500',
      minHeight: 18,
    },
    rangeText: {
      fontSize: 12,
      color: colors.textSupplementary,
    },
    amountDisplay: {
      alignItems: 'center',
      gap: 4,
    },
    amountValue: {
      fontSize: 28,
      fontWeight: '700',
      color: colors.brandPink,
    },
    amountFiat: {
      fontSize: 16,
      color: colors.textSupplementary,
      fontWeight: '600',
    },
    detailAddress: {
      fontSize: 14,
      color: colors.textSupplementary,
      fontWeight: '600',
    },
    addressHighlight: {
      color: colors.brandPink,
      fontWeight: '700',
    },
    invoiceText: {
      color: colors.textSupplementary,
      fontSize: 11,
      textAlign: 'center',
    },
    memoInput: {
      backgroundColor: colors.background,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 14,
      color: colors.textBody,
      width: '100%',
    },
    feeText: {
      fontSize: 12,
      color: colors.textSupplementary,
      fontWeight: '500',
      textAlign: 'center',
    },
    resetText: {
      color: colors.brandPink,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 4,
    },
    balanceText: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '600',
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 20,
    },
    cancelButton: {
      backgroundColor: colors.surface,
      height: 52,
      paddingHorizontal: 30,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    cancelButtonText: {
      color: colors.brandPink,
      fontSize: 16,
      fontWeight: '700',
    },
    sendButton: {
      backgroundColor: colors.surface,
      height: 52,
      paddingHorizontal: 30,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    sendButtonDisabled: {
      opacity: 0.5,
    },
    sendButtonText: {
      color: colors.brandPink,
      fontSize: 16,
      fontWeight: '700',
    },
    walletDropdownRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    walletDropdownWrapper: {
      position: 'relative',
      zIndex: 10,
    },
    walletDropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 8,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.divider,
    },
    walletDropdownText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    walletDropdownArrow: {
      fontSize: 10,
      color: colors.textSupplementary,
    },
    walletDropdownMenu: {
      position: 'absolute',
      top: '100%',
      left: 0,
      right: 0,
      marginTop: 4,
      backgroundColor: colors.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.divider,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      overflow: 'hidden',
      minWidth: 160,
    },
    walletDropdownItem: {
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    walletDropdownItemActive: {
      backgroundColor: colors.brandPink,
    },
    walletDropdownItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    walletDropdownItemTextActive: {
      color: colors.white,
    },
    walletLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSupplementary,
    },
  });
