import { StyleSheet } from 'react-native';
import type { Palette } from './palettes';

export const createTransferSheetStyles = (colors: Palette) =>
  StyleSheet.create({
    sheetBackground: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    handleIndicator: {
      backgroundColor: colors.divider,
      width: 40,
    },
    content: {
      flex: 1,
    },
    innerContent: {
      padding: 20,
      paddingBottom: 40,
      gap: 10,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textHeader,
      textAlign: 'center',
    },
    sectionLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSupplementary,
      marginTop: 6,
    },
    // --- Dropdown ---
    dropdownWrapper: {
      position: 'relative',
      zIndex: 10,
    },
    dropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: colors.divider,
    },
    dropdownText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
      flex: 1,
    },
    dropdownArrow: {
      fontSize: 10,
      color: colors.textSupplementary,
      marginLeft: 8,
    },
    dropdownMenu: {
      marginTop: 4,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.divider,
      overflow: 'hidden',
    },
    dropdownItem: {
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    dropdownItemActive: {
      backgroundColor: colors.brandPink,
    },
    dropdownItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textBody,
    },
    dropdownItemTextActive: {
      color: colors.white,
    },
    dropdownEmpty: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 13,
      color: colors.textSupplementary,
      fontStyle: 'italic',
    },
    // --- Amount ---
    amountPickerRow: {
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: colors.brandPinkLight,
      borderWidth: 1,
      borderColor: colors.brandPink,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    amountPickerValue: {
      fontSize: 26,
      fontWeight: '700',
      color: colors.brandPink,
    },
    amountPickerFiat: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '600',
      marginTop: 2,
    },
    amountPickerPlaceholder: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.brandPink,
    },
    amountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    amountInput: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: colors.brandPink,
      textAlign: 'center',
    },
    unitButton: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.divider,
    },
    unitButtonActive: {
      backgroundColor: colors.brandPink,
    },
    unitButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textSupplementary,
    },
    unitButtonTextActive: {
      color: colors.white,
    },
    convertedAmount: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '500',
      textAlign: 'center',
      minHeight: 18,
    },
    feeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      gap: 8,
    },
    boltzLogo: {
      width: 75,
      height: 75,
      borderRadius: 12,
    },
    feeText: {
      fontSize: 13,
      color: colors.textSupplementary,
      textAlign: 'left',
      fontWeight: '500',
    },
    warningText: {
      fontSize: 13,
      color: colors.red,
      textAlign: 'center',
      fontWeight: '600',
    },
    // --- Progress / Buttons ---
    progressView: {
      alignItems: 'center',
      gap: 16,
      paddingVertical: 24,
    },
    progressSummary: {
      fontSize: 28,
      fontWeight: '700',
      color: colors.brandPink,
    },
    progressRoute: {
      fontSize: 16,
      color: colors.textSupplementary,
      fontWeight: '500',
    },
    progressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      paddingVertical: 16,
      paddingHorizontal: 20,
      backgroundColor: colors.background,
      borderRadius: 12,
      marginTop: 8,
    },
    progressText: {
      fontSize: 14,
      color: colors.textBody,
      fontWeight: '500',
      textAlign: 'center',
      flex: 1,
    },
    // --- Step list (issue #62) ---
    stepList: {
      alignSelf: 'stretch',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 20,
      backgroundColor: colors.background,
      borderRadius: 12,
      marginTop: 8,
    },
    stepRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    stepIcon: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepLabel: {
      fontSize: 15,
      color: colors.textBody,
      fontWeight: '600',
      flex: 1,
    },
    stepLabelPending: {
      color: colors.textSupplementary,
      fontWeight: '500',
    },
    stepLabelFailed: {
      color: colors.red,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 20,
      marginTop: 8,
      justifyContent: 'center',
    },
    closeButton: {
      backgroundColor: colors.brandPink,
      height: 48,
      paddingHorizontal: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 8,
    },
    closeButtonText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
    closeButtonDisabled: {
      backgroundColor: colors.textSupplementary,
      opacity: 0.5,
    },
    closeButtonTextDisabled: {
      color: colors.white,
    },
    cancelButton: {
      backgroundColor: colors.surface,
      height: 52,
      paddingHorizontal: 30,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    cancelButtonText: {
      color: colors.brandPink,
      fontSize: 16,
      fontWeight: '700',
    },
    transferButton: {
      backgroundColor: colors.brandPink,
      height: 52,
      paddingHorizontal: 30,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    transferButtonText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
    buttonDisabled: {
      opacity: 0.5,
    },
  });
