import { StyleSheet } from 'react-native';
import type { Palette } from './palettes';

export const createTransactionDetailSheetStyles = (colors: Palette) =>
  StyleSheet.create({
    sheetBackground: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    handleIndicator: {
      backgroundColor: colors.divider,
      width: 40,
    },
    content: {
      padding: 20,
      paddingBottom: 40,
      gap: 14,
    },
    header: {
      alignItems: 'center',
      marginBottom: 4,
    },
    headerAmount: {
      fontSize: 30,
      fontWeight: '700',
    },
    amountIncoming: {
      color: colors.green,
    },
    amountOutgoing: {
      color: colors.red,
    },
    headerFiat: {
      fontSize: 14,
      color: colors.textSupplementary,
      marginTop: 2,
    },
    headerLabel: {
      fontSize: 14,
      color: colors.textBody,
      fontWeight: '600',
      marginTop: 6,
      textAlign: 'center',
    },
    badge: {
      alignSelf: 'center',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      marginTop: 8,
    },
    badgePending: { backgroundColor: colors.textSupplementary },
    badgeConfirmed: { backgroundColor: colors.green },
    badgeFailed: { backgroundColor: colors.red },
    badgeInfo: { backgroundColor: colors.brandPink },
    badgeText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingVertical: 8,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.divider,
    },
    rowLabel: {
      fontSize: 13,
      color: colors.textSupplementary,
      fontWeight: '500',
    },
    rowValue: {
      fontSize: 13,
      color: colors.textBody,
      fontWeight: '600',
      textAlign: 'right',
      flexShrink: 1,
    },
    rowValueMono: {
      fontFamily: 'monospace',
      fontSize: 12,
    },
    rowValueWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexShrink: 1,
    },
    headerIcon: {
      marginBottom: 8,
    },
    actions: {
      flexDirection: 'column',
      gap: 10,
      marginTop: 12,
    },
    primaryButton: {
      backgroundColor: colors.brandPink,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    primaryButtonText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
    },
    secondaryButton: {
      backgroundColor: colors.white,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.divider,
    },
    secondaryButtonText: {
      color: colors.textBody,
      fontSize: 15,
      fontWeight: '600',
    },
    info: {
      fontSize: 12,
      color: colors.textSupplementary,
      textAlign: 'center',
      marginTop: 4,
    },
    senderLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSupplementary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: -4,
    },
    senderCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.white,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.divider,
    },
    senderAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
    },
    senderAvatarPlaceholder: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    senderTextCol: {
      flex: 1,
      flexShrink: 1,
    },
    senderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    senderActionIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.brandPink,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
    },
    senderName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textHeader,
    },
    senderNpub: {
      fontSize: 12,
      color: colors.textSupplementary,
      marginTop: 2,
    },
    senderComment: {
      fontSize: 13,
      color: colors.textBody,
      fontStyle: 'italic',
      marginTop: 8,
      paddingLeft: 4,
      borderLeftWidth: 2,
      borderLeftColor: colors.brandPink,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
  });
