// Pure, deterministic procedural lightning-bolt geometry.
//
// A bolt is generated by recursive midpoint displacement: take a straight
// segment, split it at the midpoint, push that midpoint sideways (along the
// segment's perpendicular) by a random amount, then recurse into each half
// with the displacement halved. The result is a jagged polyline. At each
// level a fork can spawn — a shorter branch that shoots off at an angle —
// giving the classic tree-of-lightning look.
//
// Everything here is framework-free maths so it can be unit-tested in Jest
// (scope: src/utils). Randomness is INJECTED via an `rng: () => number`
// (values in [0,1)) so tests are fully deterministic — never call
// Math.random() at module scope or inside these functions directly.

export interface Point {
  x: number;
  y: number;
}

// One renderable polyline: the main bolt or one of its forks. `points` is the
// ordered vertex list; callers stroke it as a path. `depth` is how many fork
// generations deep this branch is (0 = trunk) so the renderer can taper width
// and opacity on deeper branches.
export interface BoltBranch {
  points: Point[];
  depth: number;
}

export interface BoltOptions {
  // Recursion depth — the number of times each segment is subdivided. Higher
  // = more vertices = more jagged. 5–7 reads as lightning; above ~9 is wasted
  // detail at screen scale.
  detail?: number;
  // Initial perpendicular displacement as a FRACTION of the bolt's straight
  // length. 0.18–0.3 looks like lightning; higher gets chaotic.
  displacement?: number;
  // Probability [0,1] that any given midpoint spawns a fork.
  forkProbability?: number;
  // Fork length as a fraction of the parent segment that spawned it.
  forkLengthRatio?: number;
  // Hard cap on fork generations so a high fork probability can't explode the
  // branch count exponentially.
  maxForkDepth?: number;
}

const DEFAULTS: Required<BoltOptions> = {
  detail: 6,
  displacement: 0.22,
  forkProbability: 0.32,
  forkLengthRatio: 0.55,
  maxForkDepth: 2,
};

function lerp(a: Point, b: Point, t: number): Point {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}

// Unit-length perpendicular to the vector a→b. Degenerate (zero-length)
// segments fall back to a fixed axis so we never divide by zero.
function perpendicular(a: Point, b: Point): Point {
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const len = Math.hypot(dx, dy);
  if (len === 0) return { x: 0, y: 1 };
  return { x: -dy / len, y: dx / len };
}

// Subdivide a→b `detail` times, displacing each new midpoint along the
// perpendicular by a random amount that halves every level. Forks discovered
// along the way are pushed into `sink` (kept flat to avoid deep recursion in
// the return value). Returns the displaced polyline for this segment.
function displaceSegment(
  a: Point,
  b: Point,
  detail: number,
  amplitude: number,
  rng: () => number,
  opts: Required<BoltOptions>,
  depth: number,
  sink: BoltBranch[],
): Point[] {
  if (detail <= 0) return [a, b];

  const mid = lerp(a, b, 0.5);
  const perp = perpendicular(a, b);
  // Centre the displacement on the segment line: rng-0.5 spans [-0.5,0.5).
  const offset = (rng() - 0.5) * 2 * amplitude;
  const displacedMid: Point = {
    x: mid.x + perp.x * offset,
    y: mid.y + perp.y * offset,
  };

  // Maybe spawn a fork from the displaced midpoint. A fork continues roughly
  // in the parent's direction but kicks off at an angle, and is itself a
  // (shorter, lower-amplitude) displaced bolt.
  if (depth < opts.maxForkDepth && rng() < opts.forkProbability) {
    const dir = { x: b.x - displacedMid.x, y: b.y - displacedMid.y };
    // Rotate the onward direction by up to ±~40° for the branch heading.
    const angle = (rng() - 0.5) * 1.4;
    const cos = Math.cos(angle);
    const sin = Math.sin(angle);
    const rotated = {
      x: dir.x * cos - dir.y * sin,
      y: dir.x * sin + dir.y * cos,
    };
    const forkEnd: Point = {
      x: displacedMid.x + rotated.x * opts.forkLengthRatio,
      y: displacedMid.y + rotated.y * opts.forkLengthRatio,
    };
    const forkPoints = displaceSegment(
      displacedMid,
      forkEnd,
      detail - 1,
      amplitude * opts.forkLengthRatio,
      rng,
      opts,
      depth + 1,
      sink,
    );
    sink.push({ points: forkPoints, depth: depth + 1 });
  }

  const left = displaceSegment(a, displacedMid, detail - 1, amplitude / 2, rng, opts, depth, sink);
  const right = displaceSegment(displacedMid, b, detail - 1, amplitude / 2, rng, opts, depth, sink);
  // Drop the duplicated join point where the two halves meet.
  return [...left, ...right.slice(1)];
}

// Generate a full bolt (trunk + forks) from `start` to `end`. Returns the
// trunk first, then any forks, so the renderer can stroke the trunk brightest.
export function generateBolt(
  start: Point,
  end: Point,
  rng: () => number,
  options: BoltOptions = {},
): BoltBranch[] {
  // Apply defaults with `??` so a caller passing an explicit `undefined`
  // (e.g. `{ detail: maybeUndefined }`) doesn't clobber the default and yield
  // NaN downstream (spread would let undefined win).
  const opts: Required<BoltOptions> = {
    detail: options.detail ?? DEFAULTS.detail,
    displacement: options.displacement ?? DEFAULTS.displacement,
    forkProbability: options.forkProbability ?? DEFAULTS.forkProbability,
    forkLengthRatio: options.forkLengthRatio ?? DEFAULTS.forkLengthRatio,
    maxForkDepth: options.maxForkDepth ?? DEFAULTS.maxForkDepth,
  };
  const length = Math.hypot(end.x - start.x, end.y - start.y);
  const amplitude = length * opts.displacement;
  const forks: BoltBranch[] = [];
  const trunk = displaceSegment(start, end, opts.detail, amplitude, rng, opts, 0, forks);
  return [{ points: trunk, depth: 0 }, ...forks];
}

// Serialise a polyline to an SVG path string ("M x y L x y L …"), the form
// Skia's `Path.MakeFromSVGString` consumes. Coordinates are rounded to keep
// the string compact. Empty / single-point inputs return ''.
export function boltToSvgPath(points: Point[]): string {
  if (points.length < 2) return '';
  const r = (n: number) => Math.round(n * 100) / 100;
  let d = `M ${r(points[0].x)} ${r(points[0].y)}`;
  for (let i = 1; i < points.length; i++) {
    d += ` L ${r(points[i].x)} ${r(points[i].y)}`;
  }
  return d;
}

// Convenience for renderers/tests: number of distinct branches a bolt has
// (trunk + forks).
export function branchCount(branches: BoltBranch[]): number {
  return branches.length;
}
